# Getting Dependencies

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import HTML
print("GPU used: ", torch.cuda.get_device_name(0))

GPU used:  GeForce 940M


# Field Hyperparameters

In [8]:
M = 10

#Reward Matrix
R = np.random.randn(M,M)
R*=10

for i in range(M):
    R[i][i]=0

# Q Matrix
Q = np.zeros((M,M))
initial_state = 1

#Learning Rate
G = 0.8

#Number of Episodes 
E = 1000 
activation = 0

# Finfing available Actions

In [4]:
def available_acts(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row>=activation)
    return av_act[0]
available_actions = available_acts(initial_state)
print(available_actions)

[0 1 3 4 5 6 7]


In [5]:
def sample_next(a):
    next_act = int(np.random.choice(a,1))
    return next_act
next_act = sample_next(available_actions)
next_act

6

In [14]:
np.cov(x,y)/50

array([[4.58333333e+02, 9.16666667e+00],
       [9.16666667e+00, 1.83333333e-01]])

In [6]:
def update(current,action,G):
    Q[current,action] = R[current,action] + G*max(Q[current])

# Training 

In [9]:
for i in range(E):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = available_acts(current_state)
    action = sample_next(available_act)
    update(current_state,action,G)

# Checking the updated reward matrix

In [14]:
R

array([[ 0.00000000e+00,  3.26028066e+01, -3.07857742e+00,
        -2.00617900e+01, -3.77291067e-01, -1.41930631e+01,
        -1.34238983e+01, -5.15073268e+00, -1.02317681e+01,
        -4.84738066e+00],
       [-1.00085222e+01,  0.00000000e+00,  1.76454467e+01,
         2.49644959e+00, -1.34652838e+01, -7.18884113e-01,
         1.49734665e+01, -1.42833855e+01,  1.17469119e+01,
        -4.03593156e+00],
       [-3.30088540e+00,  2.00454591e+01,  0.00000000e+00,
         7.85708713e+00, -1.64200939e+01,  7.07038722e+00,
         2.50879309e+01, -1.32138476e+01,  2.77542843e+00,
        -1.95769449e+01],
       [ 2.31245831e+01,  1.20909411e+01,  2.51451077e+00,
         0.00000000e+00,  1.38111559e+00,  8.06979609e+00,
        -1.09322460e+01, -2.96998020e-01,  9.87750188e+00,
        -2.68707287e+00],
       [-1.55730948e+01,  9.91634109e+00, -2.31494381e+00,
         1.54209348e+01,  0.00000000e+00,  1.43729108e+01,
         4.87653277e+00, -5.67794959e+00,  2.32403321e+01,
         9.

# Finding Path to be Traversed

In [13]:
Q = Q/np.max(Q)
print("The optimized path that is to be traversed to cover all points")
print("")
for i in range(len(Q)):
    print('State: ',i ,'; Next State : ',np.argmax(Q[i]))


The optimized path that is to be traversed to cover all points

State:  0 ; Next State :  1
State:  1 ; Next State :  2
State:  2 ; Next State :  6
State:  3 ; Next State :  0
State:  4 ; Next State :  8
State:  5 ; Next State :  6
State:  6 ; Next State :  2
State:  7 ; Next State :  8
State:  8 ; Next State :  4
State:  9 ; Next State :  4
